### ISSUE TITLE
Feature: User can see chef's profile picture

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see chef's profile picture and name.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see the face picture of the chef and name.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="748" alt="Screen Shot 2021-12-27 at 8 56 19 AM" src="https://user-images.githubusercontent.com/68756038/147492154-0a39aec5-789a-4e0d-ac76-35883320a86f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` from dbdesigner schema file.
- [x] Update `data.sql` for seed data for Gordon Ramsay profile. Include name, photoUrl, and bio. 

### ☁️ Server

- [x] Create a GET route to get a chef by id
- [x] Update `server/index.js` to make sure client and server can communicate. 
- [x] Test with HTTPie to see if you can get data from database. 
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to show face picture of the chef and name. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
