### ISSUE TITLE
Feature: User can login to their account

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can login to their account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After a user has signed up for account, they can login to their account. If user does not have an account, they can click on sign-up button to go back to create account page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="686" alt="Screen Shot 2021-12-29 at 10 37 54 AM" src="https://user-images.githubusercontent.com/68756038/147693266-0320e55a-7e36-42ed-a7eb-7d111b10de2e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Inside server/public/index.js, create a post request on app object with path '/api/auth/sign-in'.
- [x] If username and passoword are not included within user inputs, throw 401 error with message 'invalid login'
- [x] Query the database to find the "userId" and "password" for the "username"
- [x] If no user is found, throw 401 'invalid login' error
- [x] If user is found, confirm that the password included in the request body matches the "password" with `argon2.verify()`
- [x] Then, if the password does not match, throw a 401 'invalid login' error. 
- [x] If the password matches, create a payload object containing the user's "userId" and "username".
- [x] Create a new signed token with `jwt.sign()`, using the payload and your TOKEN_SECRET
- [x] Send the client a 200 response containing the payload and the token.
- [x] Catch any errors
- [x] Inside the server directory, create authorization-middleware.jsx
- [x] In authorization-middleware.jsx, require 'jsonwebtoken'
- [x] Get the 'X-Access-Token' from the request headers, and assign the return to variable 'token'
- [x] If no token is provided, throw a 401 error with the message 'authentication required'
- [x] Use jwt.verify() to verify the authenticity of the token and extract its payload
- [x] Assign the extracted payload to the user property of the req object.
- [x] Call next() (with no arguments) to let Express know to advance to its next route or middleware.
- [x] In server/public/index.js, use use method on app object, and pass in the object from authorization-middleware.jsx. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for sign-in page within sign-in.jsx
- [x] Create a button to toggle between sign-in.jsx and sign-up.jsx
- [x] Update app.jsx to include user and isAuthorized properties. 
- [x] Create a fetch request with path '/api/auth/sign-in', with method as POST
- [x] if the client provided username and password match within database, client is issued a token and stored in local storage. 
- [x] if the client provided username and password do not match within database, client receives a 400 response
- [x] Direct client to the chef profile page
- [x] Make sure app looks like wireframe, on both mobile and desktop

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
