### ISSUE TITLE
Feature: User can logout of their account

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out of their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user goes into their profile page, they will be able to sign out.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="532" alt="Screen Shot 2022-01-03 at 5 32 49 PM" src="https://user-images.githubusercontent.com/68756038/147998078-67aa3d69-855e-4b08-a35a-0398b11b7a03.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component for user profile page.
- [x] Change profile logo to 'sign out' button when user is in profile page.
- [x] Update App component to include 'handleSignOut' function.
- [x] Remove token in localStorage.
- [x] Set user to null.
- [x] Make sure app looks good on both mobile and desktop.
- [x] Set hash routing to sign in page when user logs out

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
