### ISSUE TITLE
Feature: User can search chefs by cuisine types

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search chef's by cuisine type

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can search chef's by cuisine type (ex. Italian, American, French ...etc)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="817" alt="Screen Shot 2021-12-30 at 11 13 42 AM" src="https://user-images.githubusercontent.com/68756038/147781651-89484aef-e463-43b9-8ea2-4579013a4d8f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to add more dummy chefs 

### ☁️ Server

- [x] Update `server/index.js` to handle GET request for searching chefs by cuisine type
- [x] Make the path to '/api/search/:cuisineType'
- [x] If cuisineType is a number, respond with 400 error and message
- [x] Query the data base to search chef by cuisine name
- [x] If no chef comes up, respond with error message
- [x] Otherwise, respond with the result
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for search page
- [x] Create a component for search result page
- [x] Create a component for dropdown for cuisine types
- [x] Include an Info button for chef's profile page
- [x] Include a person icon in nav-bar, when user signs in
- [x] Make sure app looks good on both mobile and desktop

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
