### ISSUE TITLE
Feature: User can see chef cuisine types

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see chef's specialty cuisine types.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see chef's specialty cuisine types. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="716" alt="Screen Shot 2021-12-28 at 11 22 41 AM" src="https://user-images.githubusercontent.com/68756038/147600031-43284195-b1db-47f7-a975-07339d527f11.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to add seed data for cuisine types. 
- [x] Apply seed data to Gordon Ramsay (chefId = 1). 

### ☁️ Server

- [x] Update `server/index.js` to handle get request for cuisine types. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component, cuisine-types.jsx, for chef's cuisine types. 
- [x] Import CuisineTypes into chef.jsx. 
- [x] Make sure app looks like wireframe, on both mobile and desktop.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
