### ISSUE TITLE
Feature: User can see chef's dish pictures

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see up to 4 pictures of chef's dishes. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see photos of chef's dish pictures along with the dish's name.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="748" alt="Screen Shot 2021-12-27 at 8 56 19 AM" src="https://user-images.githubusercontent.com/68756038/147492154-0a39aec5-789a-4e0d-ac76-35883320a86f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Download 4 sample food pictures and put them into /server/public/images directory.
- [x] Update `data.sql` to import food pictures for chefs. 
- [x] run npm run db:import command to import food pictures to database.

### ☁️ Server

- [x] Update `server/index.js` to make a GET route for individual food dishes. 
- [x] Test with HTTPie to make sure server can communicate with client. 
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to show dish name and picture. 
- [x] Make sure UI looks like the wireframe, both mobile and desktop 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
