### ISSUE TITLE
Feature: Bootstrap Refactor (auth-page)

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#26]
## ⚙️ Feature

> ##### Which feature is affected by this update?

Refactor CSS on auth page with bootstrap. 
## 📐 Plan

> ##### Summary of the technical approach to be taken.

Checkout a branch for "bootstrap". within "bootstrap" branch, checkout additional branch "auth-page". 

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

<img width="844" alt="Screen Shot 2022-01-06 at 10 51 48 AM" src="https://user-images.githubusercontent.com/68756038/148435439-ca04f309-0a5f-4fe9-9e90-57ce161f9c0b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Refactor app.jsx to show NavBar component only when user is logged in.
- [x] Make sure app looks like wireframe on both mobile and desktop.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
