### ISSUE TITLE
Design Update: Bootstrap Refactor (search, search-result pages)

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#28]
## ⚙️ Feature

> ##### Which feature is affected by this update?

Refactor CSS for search and search-result pages using bootstrap.

## 📐 Plan

> ##### Summary of the technical approach to be taken.

Make a card for each search result chefs that shows name, rating, cuisine types

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

<img width="564" alt="Screen Shot 2022-01-07 at 10 05 40 AM" src="https://user-images.githubusercontent.com/68756038/148596201-c43f474a-2965-4973-9ccc-301e93bfadca.png">

<img width="796" alt="Screen Shot 2022-01-07 at 10 06 08 AM" src="https://user-images.githubusercontent.com/68756038/148596149-469bcef6-3a05-4bda-9ca5-7a4cf37f6d11.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make transparent NavBar and add logo and menu drop down icon.
- [x] Make sure app looks good, on both mobile and desktop.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
