### ISSUE TITLE
Feature: User can review a chef

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can write reviews for chefs.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks on write a review button, a modal will pop up. They can leave a review and submit.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="831" alt="Screen Shot 2021-12-31 at 5 35 10 PM" src="https://user-images.githubusercontent.com/68756038/147842336-60f95720-d69b-4f69-8979-98d8b8c01535.png">
<img width="404" alt="Screen Shot 2021-12-31 at 5 35 43 PM" src="https://user-images.githubusercontent.com/68756038/147842337-404b8bd3-d93d-4822-9a05-174138669644.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle POST request for path '/api/review/chefId/userId'.
- [x] If chefId and userId are not positive integers, throw new ClientError with 400 status code and message.
- [x] If user does not input chefId or userId, throw new ClientError with 400 status code and message.
- [x] Query the database to post review for chef.
- [x] If user does not input review content, throw new ClientError with 400 status code and message.
- [x] Otherwise, respond with 201 status code and result.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component in chef.jsx to include a "write a review" button.
- [x] Create a component for review input modal when user clicks button, include in chef.jsx.
- [x] Create a component for confirmation modal when user submits a review, include in chef.jsx.
- [x] Make sure app looks good and like wireframe, on both mobile and desktop.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
