### ISSUE TITLE
Feature: User can see average rating for chef

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see average star rating for a chef.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see an average star rating based on all the reviews for a specific chef.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="536" alt="Screen Shot 2021-12-27 at 5 39 33 PM" src="https://user-images.githubusercontent.com/68756038/147518455-baafc794-d73c-42b4-807a-561620ef6d90.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to get the average of all the ratings for a chef
- [x] Use aggregate function AVG
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add the StarRating component to chef.jsx to show the average rating
- [x] Pass in rating as prop. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
