### ISSUE TITLE
Feature: User can see other people's reviews for a chef

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see other user's reviews.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see other user's reviews for a chef.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="519" alt="Screen Shot 2021-12-27 at 2 17 47 PM" src="https://user-images.githubusercontent.com/68756038/147511580-83916068-fda1-4536-be3b-6d96e1781a87.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to add seed data for users and reviews
- [x] Import seed data into database

### ☁️ Server

- [x] Update `server/index.js` to handle GET request for chef's reviews
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to show average star rating for a chef.
- [x] Create a component to show reviews for a chef
- [x] Make sure component looks like wireframe, on both mobile and desktop

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
