### ISSUE TITLE
Feature: User can save chefs to their watchlist

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add chefs to their watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user is in chef's profile page, they can click on save button to add chef to watchlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="629" alt="Screen Shot 2022-01-04 at 1 25 33 PM" src="https://user-images.githubusercontent.com/68756038/148125982-8cb9fe0b-cbb8-4cf1-b9aa-658d38e3a2d5.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to add dummy data (chefId, userId) for "favorites" table

### ☁️ Server

- [x] Update `server/index.js` to make a GET request for "chefs" using "favorites" table.
- [x] Make the path to '/api/userProfile/chefs/:userId'
- [x] If user does not input userId, throw 400 error and message.
- [x] If user does not input an integer as userId, throw 400 error and message.
- [x] Query the database.
- [x] Then, respond with the result.
- [x] Catch all errors.
- [x] Update 'server/index.js' to make a POST request for "favorites" using "chefId"
- [x] Make the path to '/api/userProfile/:chefId/:userId'
- [x] If user does not input chefId or userId, throw a 400 error and message
- [x] If user does not input an integer as userId or chefId, throw 400 and error message.
- [x] Query the database.
- [x] Then, respond with the result.
- [x] Catch all errors.
- [x] Test with HTTPie.
- [x] Handle all errors and respond to the client.

### ⚡ Client

- [x] Create a 'Save' button component to display on chef's profile page.
- [x] In chef.jsx, make a fetch request with POST method when user clicks "Save" button
- [x] In user-page.jsx, make a fetch request with GET method.
- [x] Create a component to show all the chefs thats been saved.
- [x] Make sure app looks good on both mobile and desktop

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
