### ISSUE TITLE
Feature: User can remove chefs from watchlist

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete chefs from their watchlist.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user is in user profile page, after clicking the red trash button, they will be able to remove chefs from their watchlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="732" alt="Screen Shot 2022-01-05 at 10 50 25 AM" src="https://user-images.githubusercontent.com/68756038/148272718-e81b60d3-7b8b-4507-982e-28962ec56de9.png">
<img width="874" alt="Screen Shot 2022-01-05 at 10 50 57 AM" src="https://user-images.githubusercontent.com/68756038/148272722-1ad1b8bf-1865-4c3d-bfa0-02c1b999f024.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to delete chefId and userId from "favorites" table. 
- [x] Make the path to '/api/userProfile/:chefId'.
- [x] Query the database. 
- [x] Respond with the result.
- [x] Catch all errors. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add a delete button component in UserPage
- [x] When user clicks delete button, request fetch using DELETE method.
- [x] Set X-Access-Token in headers for userId.
- [x] Make sure app looks good on both mobile and desktop

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
