### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/Final-Project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user

User will be able to input username and password to sign up. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="532" alt="Screen Shot 2021-12-28 at 3 06 29 PM" src="https://user-images.githubusercontent.com/68756038/147613638-2a3b611a-13d2-4f8c-8893-d81d718f0d75.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to require argon2
- [x] In index.js, make a post request on app object, and put path as '/api/auth/sign-up'
- [x] Make username and password required
- [x] Inside post request, hash the user's password with 'argon2.hash()'
- [x] Add insert sql statement to add new user to "users" table with "username" and "password" fields within database
- [x] Then, respond to the client with a 201 status code and the new user's "userId", "username", and "createdAt" timestamp.
- [x] Catch any errors
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component within pages directory, named sign-in.jsx
- [x] Add form element within sign-in.jsx
- [x] onSubmit, make a post request to save user's username and password.
- [x] Create a nav-bar component within components directory
- [x] Insert nav-bar within app.jsx
- [x] Make sure app looks like wireframe, both mobile and desktop

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
